language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DEPENDENCIES="symfony/lts:^3"
    - php: 7.3
      env: DEPENDENCIES="symfony/flex:^4"
    - php: 7.3
      env: DEPENDENCIES="symfony/flex:^5"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$DEPENDENCIES" != "" ]; then composer require --no-update $DEPENDENCIES; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer update --prefer-dist --no-interaction

script: vendor/bin/phpunit
